api:
  dashboard: true
  insecure: true

log:
  filePath: "/etc/traefik/traefik.log"
  level: DEBUG

accessLog:
  filePath: "/etc/traefik/access.log"
  bufferingSize: 50

global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: :80
    forwardedHeaders:
      trustedIPs: &trustedIps
        - !include /etc/traefik/cloudflare_ips.yml
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
    forwardedHeaders:
      trustedIPs: *trustedIps
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: ${DOMAIN_NAME}
            sans:
              - '*.${DOMAIN_NAME}'
      middlewares:
        - securityHeaders@file

serversTransport:
  insecureSkipVerify: true

providers:
  providersThrottleDuration: 2s
  file:
    filename: /etc/traefik/config.yml
    watch: true
  docker:
    watch: true
    network: proxynet
    constraints: "Label(`traefik-internal-enable`, `true`)"
    defaultRule: "Host(`{{ lower (trimPrefix `/` .Name )}}.${DOMAIN_NAME}`)"
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${EMAIL}
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

